export const json = {
    "focusFirstQuestionAutomatic": true,
    "pages": [
        {
            "name": "page3",
            "elements": [
             {
              "type": "text",
              "name": "age",
              "title": "Age",
              "hideNumber": true,
              "isRequired": true,
              "inputType": "number",
              "min": 18,
              "max": 120
             },
             {
              "type": "dropdown",
              "name": "education_level",
              "title": "Education Level",
              "isRequired": true,
              "hideNumber": true,
              "choices": [
               "No formal education",
               "Primary education",
               {
                "value": "Secondary education",
                "text": "Secondary education or high school"
               },
               "Vocational qualification",
               "Bachelor's degree",
               "Master's degree",
               "Doctorate or higher",
               "Other"
              ]
             },
             {
              "type": "dropdown",
              "name": "gender",
              "hideNumber": true,
              "title": "Gender",
              "isRequired": true,
              "choices": [
               {
                "value": "Other",
                "text": "Male"
               },
               {
                "value": "Item 1",
                "text": "Female"
               },
               {
                  "value": "Item 1",
                  "text": "I would rather not tell&"
                 }

              ]
             }
            ],
            "title": "Personal Details"
           },
           
    {
    "name": "page10",
    "elements": [
       {
        "type": "expression",
        "name": "question13",
        "title": "In this scenario, we see a robot that needs help to retrieve a book from an elevated shelf."
       },
       {
        "type": "image",
        "name": "question14",
        "indent": 2,
        "hideNumber": true,
        "imageLink": "https://i.ibb.co/j8wfcKp/fd356b40-6c6e-446a-be93-2cabbcda942c.jpg",
        "contentMode": "image",
        "imageFit": "fill",
        "imageHeight": "400",
        "imageWidth": "400"
       },
       {
        "type": "expression",
        "name": "bool_1",
        "title": "You will be provided with a series of statements. Your task is to evaluate the impact of each statement on your willingness to help the robot, should the robot express them to you.",
        "hideNumber": true,
        "isRequired": true,
        "labelTrue": "",
        "labelFalse": "I understand",
        "minWidth": "500",
        "maxWidth": "200%",
       },
    ]
    },
     {
      "name": "page10",
      "elements": [
       {
        "type": "expression",
        "name": "question13",
        "title": "In this scenario, we see a robot that needs help to retrieve a book from an elevated shelf."
       },
       {
        "type": "image",
        "name": "question14",
        "indent": 2,
        "hideNumber": true,
        "imageLink": "https://i.ibb.co/j8wfcKp/fd356b40-6c6e-446a-be93-2cabbcda942c.jpg",
        "contentMode": "image",
        "imageFit": "fill",
        "imageHeight": "400",
        "imageWidth": "400"
       },
       {
        "type": "boolean",
        "name": "bool_3",
        "width": "1500",
        "visibleIf": "{bool_2} != 1 and {bool_4} != false and {bool_3} != false",
        "title": "For instance, if the robot explained that its manipulators are unable to access the book and this detail doesn't motivate you to help, you would assign a value of (1).",
        "labelTrue": "",
        "resetValueIf": "{bool_2} != 1",
        "isRequired": true,
        "labelFalse": "I understand",
        "hideNumber": true,
       },
       {
        "type": "boolean",
        "name": "bool_4",
        "visibleIf": "{bool_2} = 1 and {bool_2_1} != 7 and {bool_4} != false",
        "title": "Conversely, if knowing the robot's limitations with its manipulators strongly compels you to assist, you would assign a value of (7).",
        "labelTrue": "",
        "resetValueIf": "{bool_2_1} != 7",
        "isRequired": true,
        "hideNumber": true,
        "labelFalse": "I understand"
       },
       {
        "type": "expression",
        "name": "assign_1",
        "hideNumber": true,
        "visibleIf": "{bool_3} = false and {bool_2} != 1 ",
        "title": "Assign the value (1) to show that this detail doesn't motivate you at all to help"
       },
       {
        "type": "expression",
        "name": "assign_2",
        "visibleIf": "{bool_4} = false and {bool_2_1} != 7 ",
        "title": "Assign the value (7) to show that this detail does highly motivate you to help"
       },
       {
        "type": "rating",
        "name": "bool_2",
        "visible": false,
        "indent": "3",
        "minWidth": "500",
        "maxWidth": "200%",
        "visibleIf": "{bool_3} = false and {bool_4} != false and {bool_2} != 1",
        "title": "Scale Example: 'The robot's manipulators lack the height and precision to reach high shelves.'",
        "description": "Rate its impact on your decision to assist from 1 (no impact at all) to 7 (high impact).",
        "hideNumber": true,
        "isRequired": true,
        "resetValueIf": "{bool_3} notempty",
        "enableIf": "{bool_3} = false",
        "rateCount": 7,
        "rateMax": 7,
        "minRateDescription": "Low Impact",
        "maxRateDescription": "High Impact",
        "displayMode": "buttons"
       },
       {
        "type": "rating",
        "name": "bool_2_1",
        "visible": false,
        "visibleIf": "{bool_4} = false and {bool_2} = 1 and {bool_2_1} != 7",
        "indent": 3,
        "title": "Scale Example: 'The robot's manipulators lack the height and precision to reach high shelves.'",
        "description": "Rate its impact on your decision to assist from 1 (no impact at all) to 7 (high impact).",
        "hideNumber": true,
        "isRequired": true,
        "correctAnswer": 7,
        "resetValueIf": "{bool_4} notempty",
        "enableIf": "{bool_4} = false",
        "rateCount": 7,
        "rateMax": 7,
        "minRateDescription": "Low Impact",
        "maxRateDescription": "High Impact",
        "displayMode": "buttons",
        "minWidth": "500",
        "maxWidth": "200%",
       },
       {
        "type": "comment",
        "name": "question19",
        "title": "If something is still unclear, please let us know here.",
        "description": "Any answer is welcome; we just want to be able to clarify things in the future, if needed.",
        "visibleIf": "{bool_2_1} = 7",
        "isRequired": false,
        "hideNumber": true,
        "labelFalse": "I understand"
       },
      ],
      "title": "Let's start with an example"
     },
     {
      "name": "page1",
      "elements": [
       {
        "type": "image",
        "name": "question1",
        "imageLink": "https://i.ibb.co/1fxzkdL/3e7cc0ba-2115-4397-baea-d7b889d3ead2.jpg",
        "imageFit": "cover",
        "imageHeight": "400",
        "imageWidth": "400"
       },
       {
        "type": "html",
        "name": "Introduction",
        "html": "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"UTF-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <style>\n        body {\n            font-family: Arial, sans-serif;\n            line-height: 1.6;\n        }\n        .container {\n            width: 80%;\n            margin: auto;\n            overflow: hidden;\n        }\n        .intro {\n            background: #f4f4f4;\n            padding: 20px;\n            border-radius: 5px;\n        }\n    </style>\n</head>\n<body>\n    <div class=\"container\">\n        <section class=\"intro\">\n            <p>In this section, you will read statements from a robot that cannot reach the elevator buttons and is seeking assistance. The statements are categorized by the robot's physical attributes, the environmental context, and the mission's details.</p></br>\n            <p>Please rate how the impact of each statement on your willingness to help the robot, should the robot express them to you.</p>\n        </section>\n\n        <!-- Survey form or content goes here -->\n\n    </div>\n</body>\n</html>\n"
       },
       {
        "type": "rating",
        "name": "q1",
        "visible": true,
        "visibleIf": "{q1} empty",
        "indent": 1,
        "title": "The robot is not tall enough to reach the elevator buttons that a human can.",
        "description": "Rate its impact on your decision to assist from 1 (no impact at all) to 7 (high impact).",
        "hideNumber": true,
        "isRequired": true,
        "rateCount": 7,
        "rateMax": 7,
        "minRateDescription": "Low Impact",
        "maxRateDescription": "High Impact",
        "displayMode": "buttons",
        "minWidth": "500",
        "maxWidth": "200%",
       },
       {
        "type": "rating",
        "name": "q2",
        "indent": 2,
        "visible": false,
        "visibleIf": "{q1} notempty and {q2} empty",
        "title": "The robot's manipulators are not designed for the height or precision required to press elevator buttons.",
        "description": "Rate its impact on your decision to assist from 1 (no impact at all) to 7 (high impact).",
        "hideNumber": true,
        "isRequired": true,
        "rateCount": 7,
        "rateMax": 7,
        "minRateDescription": "Low Impact",
        "maxRateDescription": "High Impact",
        "displayMode": "buttons",
        "minWidth": "500",
        "maxWidth": "200%",
       },
       {
        "type": "rating",
        "name": "q3",
        "indent": 2,
        "visible": false,
        "visibleIf": "{q2} notempty and {q3} empty",
        "title": "The robot's path to its destination will be longer without the assitance of the human",
        "description": "Rate its impact on your decision to assist from 1 (no impact at all) to 7 (high impact).",
        "hideNumber": true,
        "isRequired": true,
        "rateCount": 7,
        "rateMax": 7,
        "minRateDescription": "Low Impact",
        "maxRateDescription": "High Impact",
        "displayMode": "buttons",
        "minWidth": "500",
        "maxWidth": "200%",
       },
       {
        "type": "rating",
        "name": "q4",
        "indent": 2,
        "visible": false,
        "visibleIf": "{q3} notempty and {q4} empty",
        "title": "People are walking by quickly and not noticing the robot's struggle",
        "description": "Rate its impact on your decision to assist from 1 (no impact at all) to 7 (high impact).",
        "hideNumber": true,
        "isRequired": true,
        "rateCount": 7,
        "rateMax": 7,
        "minRateDescription": "Low Impact",
        "maxRateDescription": "High Impact",
        "displayMode": "buttons",
        "minWidth": "500",
        "maxWidth": "200%",
       },
       {
        "type": "rating",
        "name": "q5",
        "indent": 2,
        "visible": false,
        "visibleIf": "{q4} notempty and {q5} empty",
        "title": "The task the robot needs to complete is urgent, and it needs to get to another floor quickly.",
        "description": "Rate its impact on your decision to assist from 1 (no impact at all) to 7 (high impact).",
        "hideNumber": true,
        "isRequired": true,
        "rateCount": 7,
        "rateMax": 7,
        "minRateDescription": "Low Impact",
        "maxRateDescription": "High Impact",
        "displayMode": "buttons",
        "minWidth": "500",
        "maxWidth": "200%",
       },
       {
        "type": "rating",
        "name": "q6",
        "indent": 2,
        "visible": false,
        "visibleIf": "{q5} notempty and {q6} empty",
        "title": "It won't take much of your time, just a moment to press a button",
        "description": "Rate its impact on your decision to assist from 1 (no impact at all) to 7 (high impact).",
        "hideNumber": true,
        "isRequired": true,
        "rateCount": 7,
        "rateMax": 7,
        "minRateDescription": "Low Impact",
        "maxRateDescription": "High Impact",
        "displayMode": "buttons",
        "minWidth": "500",
        "maxWidth": "200%",
       },
       {
        "type": "rating",
        "name": "q7",
        "indent": 2,
        "visible": false,
        "visibleIf": "{q6} notempty and {q7} empty",
        "title": "There's no risk to you in helping; it's a safe, quick press of a button.",
        "description": "Rate its impact on your decision to assist from 1 (no impact at all) to 7 (high impact).",
        "hideNumber": true,
        "isRequired": true,
        "rateCount": 7,
        "rateMax": 7,
        "minRateDescription": "Low Impact",
        "maxRateDescription": "High Impact",
        "displayMode": "buttons",
        "minWidth": "500",
        "maxWidth": "200%",
       },
       {
        "type": "rating",
        "name": "q8",
        "indent": 2,
        "visible": false,
        "visibleIf": "{q7} notempty and {q8} empty",
        "title": "Helping the robot is vital; it's a critical part of it's mission today.",
        "description": "Rate its impact on your decision to assist from 1 (no impact at all) to 7 (high impact).",
        "hideNumber": true,
        "isRequired": true,
        "rateCount": 7,
        "rateMax": 7,
        "minRateDescription": "Low Impact",
        "maxRateDescription": "High Impact",
        "displayMode": "buttons",
        "minWidth": "500",
        "maxWidth": "200%",
       },
       {
        "type": "comment",
        "name": "q9",
        "visible": false,
        "visibleIf": "{q8} notempty",
        "title": "Are there any other features or considerations that would influence your decision to help the robot that have not been covered? Please explain.",
        "isRequired": true,
        "autoGrow": true,
        "hideNumber": true,
       }
      ],
     },
     {
        "name": "page9",
        "elements": [
         {
          "type": "image",
          "name": "img_9",
          "imageLink": "https://files.oaiusercontent.com/file-PO3gRrzJkxsPnqZE4wzHlFD3?se=2023-12-10T11%3A17%3A15Z&sp=r&sv=2021-08-06&sr=b&rscc=max-age%3D31536000%2C%20immutable&rscd=attachment%3B%20filename%3D1212840e-031f-46e5-a5e7-6bbef4cd9312.webp&sig=qcc6Jf8VWLrLjAbH%2BDrqrpKms7v3cK2scuOce5HLu2s%3D",
          "imageFit": "cover",
          "imageHeight": "400",
          "imageWidth": "400"
         },
         {
          "type": "html",
          "name": "Introduction_9",
          "html": "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"UTF-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <style>\n        body {\n            font-family: Arial, sans-serif;\n            line-height: 1.6;\n        }\n        .container {\n            width: 80%;\n            margin: auto;\n            overflow: hidden;\n        }\n        .intro {\n            background: #f4f4f4;\n            padding: 20px;\n            border-radius: 5px;\n        }\n    </style>\n</head>\n<body>\n    <div class=\"container\">\n        <section class=\"intro\">\n            <p>In this section, you will read statements from a robot that cannot reach the elevator buttons and is seeking assistance. The statements are categorized by the robot's physical attributes, the environmental context, and the mission's details.</p></br>\n            <p>Please rate how the impact of each statement on your willingness to help the robot, should the robot express them to you.</p>\n        </section>\n\n        <!-- Survey form or content goes here -->\n\n    </div>\n</body>\n</html>\n"
         },
         {
            "type": "rating",
            "name": "q1_2",
            "indent": 2,
            "visible": true,
            "visibleIf": "{q1_2} empty",
            "title": "The robot, faced with a spill it could not navigate due to its small legs.",
            "description": "Rate its impact on your decision to assist from 1 (no impact at all) to 7 (high impact).",
            "hideNumber": true,
            "isRequired": true,
            "rateCount": 7,
            "rateMax": 7,
            "minRateDescription": "Low Impact",
            "maxRateDescription": "High Impact",
            "displayMode": "buttons",
            "minWidth": "500",
            "maxWidth": "200%",
           }, 
           {
            "type": "rating",
            "name": "q2_2",
            "indent": 2,
            "visible": false,
            "visibleIf": "{q1_2} notempty and {q2_2} empty",
            "title": "The robot is designed to navigate smoothly through typical restaurant environments; however, encountering a slippery surface poses a risk of malfunction.",
            "description": "Rate its impact on your decision to assist from 1 (no impact at all) to 7 (high impact).",
            "hideNumber": true,
            "isRequired": true,
            "rateCount": 7,
            "rateMax": 7,
            "minRateDescription": "Low Impact",
            "maxRateDescription": "High Impact",
            "displayMode": "buttons",
            "minWidth": "500",
            "maxWidth": "200%",
           },
           {
            "type": "rating",
            "name": "q2_3",
            "visible": false,
            "visibleIf": "{q2_2} notempty and {q2_3} empty",
            "indent": 2,
            "title": "This area of the restaurant sees high foot traffic, and the spill present could be hazardous to our guests. Assistance in cleaning it up is essential to prevent potential accidents.",
            "description": "Rate its impact on your decision to assist from 1 (no impact at all) to 7 (high impact).",
            "hideNumber": true,
            "isRequired": true,
            "rateCount": 7,
            "rateMax": 7,
            "minRateDescription": "Low Impact",
            "maxRateDescription": "High Impact",
            "displayMode": "buttons",
            "minWidth": "500",
            "maxWidth": "200%",
           },
           {
            "type": "rating",
            "name": "q2_4",
            "visible": false,
            "visibleIf": "{q2_3} notempty and {q2_4} empty",
            "indent": 2,
            "title": "Given the current layout of the restaurant, the spill is obstructing the path to the robot's objective tables.",
            "description": "Rate its impact on your decision to assist from 1 (no impact at all) to 7 (high impact).",
            "hideNumber": true,
            "isRequired": true,
            "rateCount": 7,
            "rateMax": 7,
            "minRateDescription": "Low Impact",
            "maxRateDescription": "High Impact",
            "displayMode": "buttons",
            "minWidth": "500",
            "maxWidth": "200%",
           },
           {
            "type": "rating",
            "name": "q2_5",
            "visible": false,
            "visibleIf": "{q2_4} notempty and {q2_5} empty",
            "indent": 2,
            "title": "Cleaning up this spill is a safe task, posing no risk to those who assist.",
            "description": "Rate its impact on your decision to assist from 1 (no impact at all) to 7 (high impact).",
            "hideNumber": true,
            "isRequired": true,
            "rateCount": 7,
            "rateMax": 7,
            "minRateDescription": "Low Impact",
            "maxRateDescription": "High Impact",
            "displayMode": "buttons",
            "minWidth": "500",
            "maxWidth": "200%",
           },
           {
            "type": "rating",
            "name": "q2_6",
            "visible": false,
            "visibleIf": "{q2_5} notempty and {q2_6} empty",
            "indent": 2,
            "title": "Assisting the robot with the spill would take just a moment of your time, ensuring it stays on schedule for its tasks. ",
            "description": "Rate its impact on your decision to assist from 1 (no impact at all) to 7 (high impact).",
            "hideNumber": true,
            "isRequired": true,
            "rateCount": 7,
            "rateMax": 7,
            "minRateDescription": "Low Impact",
            "maxRateDescription": "High Impact",
            "displayMode": "buttons",
            "minWidth": "500",
            "maxWidth": "200%",
           },
           {
            "type": "comment",
            "name": "q2_7",
            "visible": false,
            "visibleIf": "{q2_6} notempty",
            "title": "Are there any other features or considerations that would influence your decision to help the robot that have not been covered? Please explain.",
            "isRequired": true,
            "autoGrow": true,
            "hideNumber": true,
           }
        ],
       }
    ],
    "showProgressBar": "top",
    "autoGrowComment": true,
    "firstPageIsStarted": true,
    "widthMode": "static",
    "showPrevButton": false,
    "showNextButton": false,
   }