export const BASE_URL = 'http://localhost:3000'; 

export const emotions = [
    "Joy",
    "Sadness",
    "Anger",
    "Fear",
    "Love",
    "Hate",
    "Guilt",
    "Shame",
    "Envy",
    "Pride",
    "Gratitude",
    "Hope",
    "Despair",
    "Confusion",
    "Curiosity",
    "Surprise",
    "Excitement",
    "Disappointment",
    "Contentment",
    "Loneliness",
    "Nostalgia",
    "Relief",
    "Pity",
    "Boredom",
    "Empathy",
    "Compassion",
    "Apathy",
    "Satisfaction",
    "Disgust"
  ]